const shopCategories = [
  { value: "fashion", label: "Fashion & Apparel" },
  { value: "electronics", label: "Electronics & Gadgets" },
  { value: "home_living", label: "Home, Furniture & Living" },
  { value: "beauty_personal_care", label: "Beauty & Personal Care" },
  { value: "health_wellness", label: "Health & Wellness" },
  { value: "grocery_supermarket", label: "Grocery & Supermarket" },
  { value: "food_beverage", label: "Food & Beverages" },
  { value: "bakery", label: "Bakery & Confectionery" },
  { value: "jewelry_accessories", label: "Jewelry & Accessories" },
  { value: "sports_fitness", label: "Sports & Fitness" },
  { value: "books_stationery", label: "Books, Stationery & Office Supplies" },
  { value: "toys_kids", label: "Toys, Kids & Baby Products" },
  { value: "automotive", label: "Automotive & Spare Parts" },
  { value: "pet_supplies", label: "Pet Supplies" },
  { value: "art_crafts", label: "Art, Crafts & Handmade" },
  { value: "garden_outdoor", label: "Garden, Outdoor & Tools" },
  { value: "music_instruments", label: "Music & Instruments" },
  { value: "digital_services", label: "Digital Products & Services" },
  { value: "gaming", label: "Gaming & Consoles" },
  { value: "office_equipment", label: "Office Equipment & Supplies" },
  { value: "baby_maternity", label: "Baby & Maternity" },
  { value: "industrial_scientific", label: "Industrial & Scientific" },
  { value: "travel_luggage", label: "Travel & Luggage" },
  { value: "collectibles", label: "Collectibles & Memorabilia" },
  { value: "real_estate", label: "Real Estate & Property" },
  { value: "services", label: "Professional Services" },
  { value: "events_tickets", label: "Events & Tickets" },
];
export default shopCategories;
